# Base image
FROM node:20-alpine AS base

# Create app directory
WORKDIR /app

# A wildcard is used to ensure both package.json AND package-lock.json are copied
COPY package*.json ./

# Install app dependencies
RUN npm ci

# Bundle app source
COPY . .

# Creates a "dist" folder with the production build
RUN npm run build

USER node
EXPOSE 8000

# Start the server using the production build
CMD [ "node", "dist/main.js" ]
