export const constants = {
  AUTH_TOKEN_EXPIRE: '1d',

  BASE_SERVICE_FIND_LIMIT: 6,
  BASE_SERVICE_FIND_SKIP: 0,
  BASE_SERVICE_FIND_SORT: { createdAt: 1 },

  USER_PASS_MIN_LENGTH: 6,
  USER_NAME_MIN_LENGTH: 1,

  SWAGGER_USER_EMAIL_DEFAULT: 'test@gmail.com',
  SWAGGER_USER_PASS_DEFAULT: '123456',
  SWAGGER_USER_FIRSTNAME_DEFAULT: 'firstName',
  SWAGGER_USER_LASTNAME_DEFAULT: 'lastname',

  SWAGGER_PRODUCT_IS_MY_DEFAULT: false,
  SWAGGER_PRODUCT_NAME_DEFAULT: 'Test Product',
  SWAGGER_PRODUCT_PRICE_DEFAULT: 15,
  SWAGGER_PRODUCT_CURRENCY_DEFAULT: 'USD',
  SWAGGER_PRODUCT_QUANTITY_DEFAULT: 10,
  SWAGGER_PRODUCT_ID_DEFAULT: '655cedfd17b68c6090f9b88b',
  SWAGGER_PRODUCT_USER_ID_DEFAULT: '6554e7e69941b31b3b1b2755',
  SWAGGER_PRODUCT_IMAGE_URL_DEFAULT: 'path to image',
};
